### ISSUE TITLE
paper community template

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-community-templates#1]
- [x] form for every content aspect
- [x] new just paper
- [x] tip properties for every item
- [x] small well written readme
- [x] double config remove
- [x] well written home.md
- [x] remove bogus pages
